//TUNING FOR CUSTOM GEARMOTOR
#define SPEED_PID_KP_CUSTOM		5
#define SPEED_PID_KI_CUSTOM		0.125
#define SPEED_PID_KD_CUSTOM		0
#define POS_PID_KP_CUSTOM		400
#define POS_PID_KI_CUSTOM		0
#define POS_PID_KD_CUSTOM		600
#define CUSTOM_MOTOR_MAX_RPM	155
#define CUSTOM_PPR				360

//LEGO MOTORS

#define LEGO_PPR				360

//TUNING FOR LEGO EV3 LARGE SERVO MOTOR
#define SPEED_PID_KP_EV3_LARGE	5
#define SPEED_PID_KI_EV3_LARGE	0.125
#define SPEED_PID_KD_EV3_LARGE	0
#define POS_PID_KP_EV3_LARGE	400
#define POS_PID_KI_EV3_LARGE	0
#define POS_PID_KD_EV3_LARGE	600
#define EV3_LARGE_MAX_RPM		155

//TUNING FOR LEGO EV3 MEDIUM SERVO MOTOR
#define SPEED_PID_KP_EV3_MED	4.5
#define SPEED_PID_KI_EV3_MED	0.125
#define SPEED_PID_KD_EV3_MED	0
#define POS_PID_KP_EV3_MED		2
#define POS_PID_KI_EV3_MED		0
#define POS_PID_KD_EV3_MED		0
#define EV3_MED_MAX_RPM			230

//TUNING FOR LEGO NXT LARGE SERVO MOTOR
#define SPEED_PID_KP_NXT_LARGE	5
#define SPEED_PID_KI_NXT_LARGE	0.125
#define SPEED_PID_KD_NXT_LARGE	0
#define POS_PID_KP_NXT_LARGE	400
#define POS_PID_KI_NXT_LARGE	0
#define POS_PID_KD_NXT_LARGE	600
#define NXT_LARGE_MAX_RPM		155
